---@type overseer.TemplateFileDefinition
---@module "overseer.template"
return {
  name = "neocov: generate coverage",
  builder = function(params)
    local fullpath = vim.fn.expand("%:p")
    if fullpath == "" then return { cmd = { "echo", "No active file found" } } end
    local basename = vim.fn.expand("%:t")

    require("nvim-neocov.log").debugf("Staring generate coverage task for %s", basename)
    local cfg = require("nvim-neocov.config").config
    local cmd = cfg.cmd(fullpath)
    --TODO(JON): Actually use the params

    ---@module "overseer.task"
    ---@type overseer.TaskDefinition
    return {
      name = "Generate & Show Coverage for " .. basename,
      cmd = cmd.cmd,
      cwd = cmd.cwd,
      env = cmd.env,
      metadata = {
        coverage = nil,
      },
      components = {
        -- "neocov.clear_coverage_markers",
        { "neocov.on_complete_coverage", file = fullpath },
        "default",
      },
    }
  end,
  desc = "Generate coverage for a file and then load and annotate affected files",
  tags = { "TEST" },
  params = {
    annotate = {
      desc = "Annotate open buffers after generating the coverage",
      type = "boolean",
      default = true,
    },
  },
  --TODO(JON): Wire up filetypes
  -- condition = {
  --   filetype = {},
  -- },
}

-- -- Safely check if overseer is installed before registering
-- local has_overseer, overseer = pcall(require, "overseer")
-- if has_overseer then
--   -- Registers your file via its subpath format
--   overseer.register_template("neocov.generate")
-- end

-- User's Neovim configuration file
-- require("overseer").setup({
--   templates = { "builtin", "neocov.generate" },
-- })

-- local overseer = require("overseer")
--
-- overseer.add_template_hook({
--   -- Filter by the template provider module name (your plugin path)
--   module = "neocov.generate",
--   -- Or filter strictly by the name defined inside your template file
--   name = "NeoCov: Generate Coverage",
-- }, function(task_defn, util)
--   -- 1. Completely overwrite your components array
--   task_defn.components = { "default", { "on_complete_notify", statuses = { "SUCCESS" } } }
--
--   -- 2. Alternatively, use helper utilities to append components instead of erasing them
--   util.add_component(task_defn, { "on_output_quickfix", open = true })
--
--   -- 3. Or remove a specific component you bundled
--   util.remove_component(task_defn, "on_output_write_file")
-- end)

-- local overseer = require("overseer")
--
-- overseer.add_template_hook({
--   -- Catch tasks generated by the neotest overseer strategy adapter
--   module = "neotest",
-- }, function(task_defn, util)
--   -- Append a custom inline component to handle post-execution logic
--   util.add_component(task_defn, {
--     "on_complete",
--     on_complete = function(self, task)
--       -- Check if the tests passed successfully
--       if task.status == "SUCCESS" then
--         -- Run your coverage task using its registered module identifier
--         overseer.run_template({ name = "neocov.generate" }, function(cov_task)
--           if cov_task then
--             -- Optional: configure behavior when the coverage task runs
--           else
--             vim.notify("Failed to initiate neocov template", vim.log.levels.WARN)
--           end
--         end)
--       end
--     end,
--   })
-- end)
